Removing PNG requirement for uploaded image
kiva/protocol-sdk-issuer pull request #12
Opened 2020-12-14 21:12 UTC by natesulat

2020-12-15 23:54 UTC, horationunez requested changes

2020-12-15 23:54 UTC, horationunez commented on src/ui/screens/WebcamCaptureTool.tsx
> +    const parts: string[] = dataUri.split(",", 2);
We should check errors here and default to a certain type, similar to what you did in the verifier side.

2020-12-15 23:54 UTC, horationunez commented on src/ui/screens/WebcamCaptureTool.tsx
> +    // This relies on the ImageUpload component returning base64 encoded images
See comment above.

2020-12-15 23:54 UTC, horationunez commented on src/ui/screens/WebcamCaptureTool.tsx
>        "photo~attach": photo
Not a critical thing, but using the exact field name here might create problems if we ever have to take a picture that will be stored in a different credential field.

2020-12-17 18:56 UTC, michelleinez approved these changes

2020-12-19 16:06 UTC, horationunez approved these changes

2020-12-21 17:25 UTC, merged