[PRO-2779][v1] - Pre-commit hooks
kiva/protocol-sdk-issuer pull request #27
Opened 2021-03-04 07:45 UTC by natesulat

Similar to https://github.com/kiva/protocol-sdk-verifier/pull/14, this doesn't solve all our problems, but it's a start

2021-03-04 13:13 UTC, horationunez requested changes

2021-03-04 13:13 UTC, horationunez commented on package.json
> +    "postinstall": "sh ./tools/setup/setup_hooks.sh",
I think this might be helpful for the people of Kiva but could be invasive to the people that just download the package.

2021-03-04 13:13 UTC, horationunez commented on tools/bundle/static_file_generator.sh
> +sh ./tools/setup/setup_hooks.sh
I think hooks could be advice as part of the documentation, and as mandatory for collaborators. But an static file generator shouldn't register hooks in the user's environment.

2021-03-04 19:17 UTC, natesulat commented
For the record I don't see a `postinstall` script as any more invasive than asking people to install our NPM project, but I don't want to make anyone unnecessarily uncomfortable.

Also, people may have their own hooks set up. Overwriting those hook scripts with ours would definitely be a Bad Thing.

2021-03-10 17:27 UTC, michelleinez approved these changes

2021-03-22 22:39 UTC, merged